### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by jhuyvu** [jaspenlind/nordvpn-server-lister#1]
Hi, 
I tried install your script but got this problem. How can I fix it?

**404 Not Found: nordvpn-server-lister@latest**

Thanks

**Comment by jaspenlind** [comment]
Hi @jhuyvu .

I haven't published this repo to npm yet, that's why you get the 404.

In the meanwhile, you can install it from here: npm install -g https://github.com/jaspenlind/nordvpn-server-lister/releases/download/v0.1.0/nordvpn-server-lister-0.1.0.tgz

There's still some improvements I'd like to do to the filters and README before publishing it to npm. I'll look into that.

**Comment by jaspenlind** [comment]
This package is now published to [npm](https://www.npmjs.com/package/nordvpn-server-lister) if you're still interested
